### PR TITLE
Fix report test

### PR DESCRIPTION
**Pull request by olegbespalov**
## What?

This PR adds an argument that was introduced in #3204

## Why?

Currently, the test fails with:

```
 # go.k6.io/k6/cmd [go.k6.io/k6/cmd.test]
Error: cmd/report_test.go:40:35: not enough arguments in call to execution.NewScheduler
```

https://github.com/grafana/k6/actions/runs/7488727602/job/20383819709?pr=3530

## Checklist

- [x] I have performed a self-review of my code.
- [ ] I have added tests for my changes.
- [ ] I have run linter locally (`make lint`) and all checks pass.
- [x] I have run tests locally (`make tests`) and all tests pass.
- [ ] I have commented on my code, particularly in hard-to-understand areas.

## Related PR(s)/Issue(s)

https://github.com/grafana/k6/pull/3525

### CODE REVIEW

**Comment by olegbespalov** [comment]
Closed in favor of https://github.com/grafana/k6/pull/3531
